FROM maven:3.9-eclipse-temurin-17 AS builder

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean compile -DskipTests -q

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=dev", "-q"]
